jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank_rest
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.xml
    enabled: true
    user: postgres
    password: root
    default-schema: public
    liquibase-schema: public

logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate: OFF
    org.hibernate.type.descriptor.sql: TRACE
    liquibase: OFF
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  card-encryption-key: ${CARD_ENCRYPTION_KEY:DefaultTestKey123456789012}

token:
  jwt_cookie_name: shadrin-jwt
  jwt_refresh_cookie_name: shadrin-jwt-refresh
  jwt_refresh_expiration_ms: 180000
  access_token_validity_millis: 600000 #10 min
  refresh_token_validity_millis: 864000000 # 10 days
  token_secret: # оставить здесь или в .env?




